language: node_js
node_js:
  - '12.10'

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  skip-cleanup: true
  local-dir: .vuepress/dist
  on:
    branch: master

